[package]
name = "helloworld_in_riscv_and_baremetal_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt = "0.2.0"
riscv-rt = { version = "0.11.0", features = ["s-mode"] }
